AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks-FE on Amazon Web Services'
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - PrivateSubnetID
      - StarRocksServerSecurityGroup
    - Label:
        default: EC2 configuration
      Parameters:
      - KeyPairName
    - Label:
        default: AMI's id
      Parameters:
      - AmiId
    - Label:
        default: Node type configuration
      Parameters:
      - FeNodeInstanceType
    - Label:
        default: Fe configuration
      Parameters:
      - FeNodeCount
      - LogDir
      - SysLogLevel
      - MetaDir
      - HttpPort
      - RpcPort
      - QueryPort
      - EditLogPort
      - BeInstancePrivateIp1
      - BeInstancePrivateIp2
      - BeInstancePrivateIp3
      - BeInstancePrivateIp4
      - BeInstancePrivateIp5
      - BeInstancePrivateIp6
    ParameterLabels:
      PrivateSubnetID:
        default: Private subnet ID
      StarRocksServerSecurityGroup:
        default: StarRocks Server Security Group
      KeyPairName:
        default: Key pair name
      AmiId:
        default: AMI with StarRocks
      FeNodeInstanceType:
        default: Fe instance type
      FeNodeCount:
        default: Fe Node Count
      LogDir:
        default: Dir to save fe log
      SysLogLevel:
        default: Sys Log Level
      MetaDir:
        default: Meta data dir
      HttpPort:
        default: Fe http port
      RpcPort:
        default: Fe rpc port
      QueryPort:
        default: Fe query port
      EditLogPort:
        default: Fe edit log port
      BeInstancePrivateIp1:
        default: be ip 1
      BeInstancePrivateIp2:
        default: be ip 2
      BeInstancePrivateIp3:
        default: be ip 3
      BeInstancePrivateIp4:
        default: be ip 4
      BeInstancePrivateIp5:
        default: be ip 5
      BeInstancePrivateIp6:
        default: be ip 6
Parameters: 
  PrivateSubnetID: 
    Description: The Private Subnet ID that you want to deploy Fe nodes.
    Type: String
  StarRocksServerSecurityGroup: 
    Description: StarRocks Server Security Group.
    Type: String
  KeyPairName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs allow you to securely connect to your instance after it launches.
  AmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: String
  FeNodeInstanceType: 
    Description: Amazon EC2 instance type for the fe nodes.
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
  FeNodeCount:
    Description: Fe Node Count
    Type: Number
  LogDir:
    Description: Dir to save log, please to fill in the absolute path
    Type: String
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  MetaDir:
    Description: Dir to save mete data, please to fill in the absolute path
    Type: String
  HttpPort:
    Description: Fe http port
    Type: String
  RpcPort:
    Description: Fe rpc port
    Type: String
  QueryPort:
    Description: Fe query port
    Type: String
  EditLogPort:
    Description: Fe edit log port
    Type: String
  BeInstancePrivateIp1:
    Description: be ip 1
    Type: String
  BeInstancePrivateIp2:
    Description: be ip 2
    Type: String
  BeInstancePrivateIp3:
    Description: be ip 3
    Type: String
  BeInstancePrivateIp4:
    Description: be ip 4
    Type: String
  BeInstancePrivateIp5:
    Description: be ip 5
    Type: String
  BeInstancePrivateIp6:
    Description: be ip 6
    Type: String
Conditions:
  3NodesCondition: !Equals [!Ref 'FeNodeCount', '3']
Resources:
  FeMasterInstance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install fe master instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      InstanceType: !Ref FeNodeInstanceType
      SubnetId: !Ref PrivateSubnetID
      SecurityGroupIds:
      - !Ref StarRocksServerSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource FeMasterInstance --region ${AWS::Region}
          cd /home/ec2-user/starrocks/StarRocks-2.0.1/fe
          mkdir -p meta
          source /etc/profile
          bin/start_fe.sh --daemon
          python /home/ec2-user/tool/cluster-tool.py ${BeInstancePrivateIp1} ${BeInstancePrivateIp2} ${BeInstancePrivateIp3} ${BeInstancePrivateIp4} ${BeInstancePrivateIp5} ${BeInstancePrivateIp6} >> addbe.log
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource FeMasterInstance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"
  FeFollowerInstance1:
    Condition: 3NodesCondition
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install fe follower instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      InstanceType: !Ref FeNodeInstanceType
      SubnetId: !Ref PrivateSubnetID
      SecurityGroupIds:
      - !Ref StarRocksServerSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource FeFollowerInstance1 --region ${AWS::Region}
          cd /home/ec2-user/starrocks/StarRocks-2.0.1/fe
          mkdir -p meta
          source /etc/profile
          bin/start_fe.sh --helper ${FeMasterInstance.PrivateIp}:9010 --daemon
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource FeFollowerInstance1 --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"
  FeFollowerInstance2:
    Condition: 3NodesCondition
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install fe follower instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      InstanceType: !Ref FeNodeInstanceType
      SubnetId: !Ref PrivateSubnetID
      SecurityGroupIds:
      - !Ref StarRocksServerSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource FeFollowerInstance2 --region ${AWS::Region}
          cd /home/ec2-user/starrocks/StarRocks-2.0.1/fe
          mkdir -p meta
          source /etc/profile
          bin/start_fe.sh --helper ${FeMasterInstance.PrivateIp}:9010 --daemon
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource FeFollowerInstance2 --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"
  ToolInstance:
    Condition: 3NodesCondition
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install tool instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      InstanceType: !Ref FeNodeInstanceType
      SubnetId: !Ref PrivateSubnetID
      SecurityGroupIds:
      - !Ref StarRocksServerSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource ToolInstance --region ${AWS::Region}
          cd /home/ec2-user/starrocks/StarRocks-2.0.1/fe
          touch addToMaster.py
          chmod +x addToMaster.py
          echo '#!/usr/bin/python' >> addToMaster.py
          echo '# -*- coding: UTF-8 -*-' >> addToMaster.py
          echo 'import MySQLdb' >> addToMaster.py
          echo 'import sys' >> addToMaster.py
          echo 'import time' >> addToMaster.py
          echo 'import os' >> addToMaster.py
          echo 'time.sleep(30)' >> addToMaster.py
          echo 'db = MySQLdb.connect(host = sys.argv[1], user = '"'"'root'"'"', passwd = '"'"''"'"', port = 9030, connect_timeout=10)' >> addToMaster.py
          echo 'cursor = db.cursor()' >> addToMaster.py
          echo 'cursor.execute("ALTER SYSTEM ADD FOLLOWER '"'"'%s:9010'"'"'"%sys.argv[2])' >> addToMaster.py
          echo 'cursor.execute("ALTER SYSTEM ADD FOLLOWER '"'"'%s:9010'"'"'"%sys.argv[3])' >> addToMaster.py
          echo 'data = cursor.fetchone()' >> addToMaster.py
          echo 'db.close()' >> addToMaster.py
          python addToMaster.py ${FeMasterInstance.PrivateIp} ${FeFollowerInstance1.PrivateIp} ${FeFollowerInstance2.PrivateIp}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource ToolInstance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"
Outputs:
  FeMasterInstance:
    Description: fe master instance
    Value: !Ref FeMasterInstance
  FeMasterInstancePrivateIp:
    Value: !GetAtt FeMasterInstance.PrivateIp
  FeFollowerInstance1:
    Condition: 3NodesCondition
    Description: fe follower instance1
    Value: !Ref FeFollowerInstance1
  FeFollowerInstance1PrivateIp:
    Condition: 3NodesCondition
    Value: !GetAtt FeFollowerInstance1.PrivateIp
  FeFollowerInstance2:
    Condition: 3NodesCondition
    Description: fe follower instance2
    Value: !Ref FeFollowerInstance2
  FeFollowerInstance2PrivateIp:
    Condition: 3NodesCondition
    Value: !GetAtt FeFollowerInstance2.PrivateIp