AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks on Amazon Web Services in a new VPC.'
Metadata:
  LICENSE: Apache License Version 2.0
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying StatRocsk into an new VPC"
    Order: "1"
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - AvailabilityZones
      - PrivateSubnetID
    - Label:
        default: EC2 configuration
      Parameters:
      - KeyPairName
    - Label:
        default: AMI's id
      Parameters:
      - AmiId
    - Label:
        default: StarRocks Cluster configuration
      Parameters:
      - FeNodeCount
      - FeNodeInstanceType
      - BeNodeCount
      - BeNodeInstanceType
      - BrokerNodeCount
      - BrokerNodeInstanceType
    - Label:
        default: BE configuration
      Parameters:
      - SysLogDir
      - SysLogLevel
      - BePort
      - BeRpcPort
      - WebserverPort
      - HeartbeatServicePort
      - BrpcPort
      - VolumeType
      - VolumeSize
    - Label:
        default: Fe configuration
      Parameters:
      - LogDir
      - SysLogLevel
      - MetaDir
      - HttpPort
      - RpcPort
      - QueryPort
      - EditLogPort
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      PrivateSubnetID:
        default: Private subnet ID
      KeyPairName:
        default: Key pair name
      AmiId:
        default: Ami id
      FeNodeCount:
        default: Number of StarRocks Fe
      FeNodeInstanceType:
        default: Fe instance type
      BeNodeCount:
        default: Number of StarRocks Be
      BeNodeInstanceType:
        default: Be instance type
      BrokerNodeCount:
        default: Number of StarRocks Broker
      BrokerNodeInstanceType:
        default: Broker instance type
      SysLogDir:
        default: Dir to save be sys log
      SysLogLevel:
        default: Sys Log Level
      BePort:
        default: Be port
      BeRpcPort:
        default: Be Rpc port
      WebserverPort:
        default: Webserver port
      HeartbeatServicePort:
        default: Heartbeat service port
      BrpcPort:
        default: Brpc port
      VolumeType:
        default: Volume type of Be nodes
      VolumeSize:
        default: Volume size of Be nodes
      LogDir:
        default: Dir to save fe log
      SysLogLevel:
        default: Sys Log Level
      MetaDir:
        default: Meta data dir
      HttpPort:
        default: Fe http port
      RpcPort:
        default: Fe rpc port
      QueryPort:
        default: Fe query port
      EditLogPort:
        default: Fe edit log port
Parameters:
  AvailabilityZones:
    Description: 'List of Availability Zones (AZs) to use for the VPC subnets. More AZs improve the availability of the system, and fewer AZs reduce the cost of data traffic between AZs).'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PrivateSubnetID:
    Description: The Private Subnet ID that you want to deploy Fe nodes.
    Type: String
    Default: 10.0.0.0/19
  KeyPairName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs allow you to securely connect to your instance after it launches.
    Default: CFT-Test
  AmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: String
    Default: ami-0e11bc1aa58311f73
  FeNodeCount:
    Type: String
    Default: 1
    Description: Number of StarRocks Fe
    AllowedValues: 
      - 1
      - 2
      - 3
  FeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for fe instances.
    Type: String
  BeNodeCount:
    Type: String
    Default: 3
    Description: Number of StarRocks Be
    AllowedValues: 
      - 3
      - 4
      - 5
      - 6
  BeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for be instances.
    Type: String
  BrokerNodeCount:
    Type: String
    Default: 3
    Description: Number of StarRocks Broker
    AllowedValues: 
      - 3
      - 4
      - 5
      - 6
  BrokerNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for Broker instances.
    Type: String
  SysLogDir:
    Description: Dir to save be log, please to fill in the absolute path
    Type: String
    Default: To be determined
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  BePort:
    Description: Be port
    Type: String
    Default: To be determined
  BeRpcPort:
    Description: Be Rpc port
    Type: String
    Default: To be determined
  WebserverPort:
    Description: Webserver port
    Type: String
    Default: To be determined
  HeartbeatServicePort:
    Description: Heartbeat service port
    Type: String
    Default: To be determined
  BrpcPort:
    Description: Brpc port
    Type: String
    Default: To be determined
  VolumeType: 
    Type: String
    Description: EBS volume type (data) to be attached to node in GBs [gp2,gp3,st1], one volume for data storage is mounted automatically by CloudFormation stack.
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - st1
      - io1
  VolumeSize: 
    Type: String
    Description: EBS volume size (data) to be attached to node in GBs.
    Default: 50
  LogDir:
    Description: Dir to save log, please to fill in the absolute path
    Type: String
    Default: To be determined
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  MetaDir:
    Description: Dir to save mete data, please to fill in the absolute path
    Type: String
    Default: To be determined
  HttpPort:
    Description: Fe http port
    Type: String
    Default: To be determined
  RpcPort:
    Description: Fe rpc port
    Type: String
    Default: To be determined
  QueryPort:
    Description: Fe query port
    Type: String
    Default: To be determined
  EditLogPort:
    Description: Fe edit log port
    Type: String
    Default: To be determined
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-northwest-1.amazonaws.com.cn/cf-templates-ieth34xkk4vz-cn-northwest-1/2022053hRF-aws-vpc.template.yaml
      Parameters:
        AvailabilityZones:
          !Join
          - ','
          - !Ref AvailabilityZones
        NumberOfAZs: '2'
        CreateNATGateways: 'true'
        PrivateSubnet1ACIDR: 10.0.128.0/20
        PrivateSubnet2ACIDR: 10.0.144.0/20
        PublicSubnet1CIDR: 10.0.160.0/20
        PublicSubnet2CIDR: 10.0.176.0/20
        VPCCIDR: 10.0.0.0/16
        CreateAdditionalPrivateSubnets: 'false'
        CreatePublicSubnets: 'true'
        CreatePrivateSubnets: 'true'
        CreateVPCFlowLogsToCloudWatch: 'false'
        PrivateSubnet1BCIDR: 10.0.192.0/21
        PrivateSubnet2BCIDR: 10.0.200.0/21
        PrivateSubnet3ACIDR: 10.0.64.0/19
        PrivateSubnet3BCIDR: 10.0.208.0/21
        PrivateSubnet4ACIDR: 10.0.96.0/19
        PrivateSubnet4BCIDR: 10.0.216.0/21
        PrivateSubnetATag1: Network=Private
        PrivateSubnetATag2: ''
        PrivateSubnetATag3: ''
        PrivateSubnetBTag1: Network=Private
        PrivateSubnetBTag2: ''
        PrivateSubnetBTag3: ''
        PublicSubnet3CIDR: 10.0.160.0/20
        PublicSubnet4CIDR: 10.0.176.0/20
        PublicSubnetTag1: Network=Public
        PublicSubnetTag2: ''
        PublicSubnetTag3: ''
        VPCFlowLogsCloudWatchKMSKey: ''
        VPCFlowLogsLogGroupRetention: 14
        VPCFlowLogsMaxAggregationInterval: 600
        VPCFlowLogsTrafficType: REJECT
        VPCTenancy: default
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-northwest-1.amazonaws.com.cn/cf-templates-ieth34xkk4vz-cn-northwest-1/2022055UhM-bastion.template.yaml
      Parameters:
        KeyPairName: !Ref KeyPairName
        ParentStack: ppll
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        ImageID: ami-019ef4a13f29ddecb
        RemoteAccessCIDR: 0.0.0.0/0
        AdminEmailAddress: ccc@ccc.com
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-northwest-1.amazonaws.com.cn/cf-templates-ieth34xkk4vz-cn-northwest-1/2022055W0L-securitygroups.template.yaml
      Parameters:
        AccessCIDR: 0.0.0.0/0
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        BastionSecurityGroupID: !GetAtt BastionStack.Outputs.BastionSecurityGroupID
  BeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-northwest-1.amazonaws.com.cn/cf-templates-ieth34xkk4vz-cn-northwest-1/2022055OsE-starrocks_be.template.yaml
      Parameters:
        PrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        AmiId: !Ref AmiId
        BeNodeInstanceType: !Ref BeNodeInstanceType
        SysLogDir: !Ref SysLogDir
        SysLogLevel: !Ref SysLogLevel
        BePort: !Ref BePort
        BeRpcPort: !Ref BeRpcPort
        WebserverPort: !Ref WebserverPort
        HeartbeatServicePort: !Ref HeartbeatServicePort
        BrpcPort: !Ref BrpcPort
        VolumeType: !Ref VolumeType
        VolumeSize: !Ref VolumeSize
  FeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-northwest-1.amazonaws.com.cn/cf-templates-ieth34xkk4vz-cn-northwest-1/20220551wM-starrocks_fe.template.yaml
      Parameters:
        PrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        AmiId: !Ref AmiId
        FeNodeInstanceType: !Ref FeNodeInstanceType
        LogDir: !Ref LogDir
        SysLogLevel: !Ref SysLogLevel
        MetaDir: !Ref MetaDir
        HttpPort: !Ref HttpPort
        RpcPort: !Ref RpcPort
        QueryPort: !Ref QueryPort
        EditLogPort: !Ref EditLogPort
        BeInstancePrivateIp1: !GetAtt BeStack.Outputs.BeInstancePrivateIp1
        BeInstancePrivateIp2: !GetAtt BeStack.Outputs.BeInstancePrivateIp2
        BeInstancePrivateIp3: !GetAtt BeStack.Outputs.BeInstancePrivateIp3
        