AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks-BE on Amazon Web Services'
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - PrivateSubnetID
    - Label:
        default: Node type configuration
      Parameters:
      - BeInstanceType
    - Label:
        default: BE configuration
      Parameters:
      - SysLogLevel
      - SysLogDir
      - SysLogRollNum
      - SysLogRollMode
      - SysLogVerboseModules
      - BePort
      - BeRpcPort
      - WebserverPort
      - HeartbeatServicePort
      - BrpcPort
      - BitmapMaxFilterRatio
      - LogBufferLevel
      - TrashFileExpireTimeSec
      - DefaultRowsetType
      - MemLimit
      - TcUseMemoryMin
      - FragmentPoolThreadNumMax
      - ThriftClientRetryIntervalMs
      - EnableMetricCalculator
      - DisableStoragePageCache
      - DisableColumnPool
    ParameterLabels:
      PrivateSubnetID:
        default: Private subnet ID
      BeInstanceType:
        default: Be instance type
      SysLogLevel:
        default: Sys Log Level
      SysLogDir:
        default: Dir to save be sys log
      SysLogRollNum: 
        default: Sys log roll num
      SysLogRollMode:
        default: Sys log roll mode
      SysLogVerboseModules:
        default: Sys log verboseModules
      BePort:
        default: Be port
      BeRpcPort:
        default: Be Rpc port
      WebserverPort:
        default: Webserver port
      HeartbeatServicePort:
        default: Heartbeat service port
      BrpcPort:
        default: Brpc port
      BitmapMaxFilterRatio:
        default: Bitmap max filter ratio
      LogBufferLevel:
        default: Log buffer level
      TrashFileExpireTimeSec:
        default: Trash file expireTime sec
      DefaultRowsetType:
        default: Default rowset type
      MemLimit:
        default: Mem limit
      TcUseMemoryMin:
        default: Tc UseMemory min
      FragmentPoolThreadNumMax:
        default: Fragment pool thread num max
      ThriftClientRetryIntervalMs:
        default: Thrift client retry interval ms
      EnableMetricCalculator:
        default: Enable metric calculator
      DisableStoragePageCache:
        default: Disable storage page cache
      DisableColumnPool:
        default: Disable column pool
Parameters: 
  PrivateSubnetID: 
    Description: The Private Subnet ID that you want to deploy Fe nodes.
    Type: String
  BeInstanceType: 
    Description: Amazon EC2 instance type for the be nodes.
    Type: String
    Default: i3.2xlarge
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  SysLogDir:
    Description: Dir to save be log, please to fill in the absolute path
    Type: String
  SysLogRollNum: 
    Description: Sys log roll num
    Type: String
  SysLogRollMode:
    Description: Sys log roll mode
    Type: String
  SysLogVerboseModules:
    Description: Sys log verboseModules
    Type: String
  BePort:
    Description: Be port
    Type: String
  BeRpcPort:
    Description: Be Rpc port
    Type: String
  WebserverPort:
    Description: Webserver port
    Type: String
  HeartbeatServicePort:
    Description: Heartbeat service port
    Type: String
  BrpcPort:
    Description: Brpc port
    Type: String
  BitmapMaxFilterRatio:
    Description: Bitmap max filter ratio
    Type: String
  LogBufferLevel:
    Description: Log buffer level
    Type: String
  TrashFileExpireTimeSec:
    Description: Trash file expireTime sec
    Type: String
  DefaultRowsetType:
    Description: Default rowset type
    Type: String
  MemLimit:
    Description: Mem limit
    Type: String
  TcUseMemoryMin:
    Description: Tc UseMemory min
    Type: String
  FragmentPoolThreadNumMax:
    Description: Fragment pool thread num max
    Type: String
  ThriftClientRetryIntervalMs:
    Description: Thrift client retry interval ms
    Type: String
  EnableMetricCalculator:
    Description: Enable metric calculator
    Type: String
    AllowedValues: 
      - True
      - False
  DisableStoragePageCache:
    Description: Disable storage page cache
    Type: String
    AllowedValues: 
      - True
      - False
  DisableColumnPool:
    Description: Disable column pool
    Type: String
    AllowedValues: 
      - True
      - False
Resources:
  FeInstance:
    Type: AWS::EC2::Instance
    Metadata:
    Properties:
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"