AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks-FE on Amazon Web Services'
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - PrivateSubnetID
    - Label:
        default: Node type configuration
      Parameters:
      - FeInstanceType
    - Label:
        default: Fe configuration
      Parameters:
      - LogDir
      - SysLogLevel
      - MetaDir
      - HttpPort
      - RpcPort
      - QueryPort
      - EditLogPort
      - MysqlServiceNioEnabled
      - EnableSparkLoad
      - SparkHomeDefaultDir
      - YarnClientPath
      - CatalogTrashExpireSecond
      - LogRollSizeMb
      - SysLogRollNum
      - AuditLogDir
      - AuditLogModules
      - MetaDelayTolerationSecond
      - QeMaxConnection
      - MaxConnPerUser
      - QeQueryTimeoutSecond
      - QeSlowLogMs
      - LabelKeepMaxSecond
      - EnableNewPlanner
      - StreamLoadDefaultTimeoutSecond
      - TabletCreateTimeoutSecond
      - MaxCreateTableTimeoutSecond
      - ThriftClientTimeoutMs
      - CatalogTryLockTimeoutMs
      - IgnoreUnknownLogId
      - LatestAmiId
    ParameterLabels:
      PrivateSubnetID:
        default: Private subnet ID
      FeInstanceType:
        default: Fe instance type
      LogDir:
        default: Dir to save fe log
      SysLogLevel:
        default: Sys Log Level
      MetaDir:
        default: Meta data dir
      HttpPort:
        default: Fe http port
      RpcPort:
        default: Fe rpc port
      QueryPort:
        default: Fe query port
      EditLogPort:
        default: Fe edit log port
      MysqlServiceNioEnabled:
        default: Mysql service nio enabled
      EnableSparkLoad:
        default: Enable spark load
      SparkHomeDefaultDir:
        default: Spark home default dir
      YarnClientPath:
        default: Yarn client path
      CatalogTrashExpireSecond:
        default: Catalog trash expire second
      LogRollSizeMb:
        default: Log roll size mb
      SysLogRollNum:
        default: Sys log roll num
      AuditLogDir: 
        default: Audit log dir
      AuditLogModules:
        default: Audit log modules
      MetaDelayTolerationSecond:
        default: Meta delay toleration second
      QeMaxConnection:
        default: Qe max connection
      MaxConnPerUser:
        default: Max connPerUser
      QeQueryTimeoutSecond:
        default: Qe query timeout second
      QeSlowLogMs: 
        default: Qe slow log ms
      LabelKeepMaxSecond:
        default: Label keep max second
      EnableNewPlanner:
        default: Enable new planner
      StreamLoadDefaultTimeoutSecond:
        default: StreamLoad default timeout second
      TabletCreateTimeoutSecond:
        default: Tablet create timeout second
      MaxCreateTableTimeoutSecond:
        default: Max create table timeout second
      ThriftClientTimeoutMs:
        default: Thrift client timeout ms
      CatalogTryLockTimeoutMs:
        default: Catalog try lock timeout ms
      IgnoreUnknownLogId:
        default: Ignore unknown logId
      LatestAmiId:
        default: AMI with StarRocks
Parameters: 
  PrivateSubnetID: 
    Description: The Private Subnet ID that you want to deploy Fe nodes.
    Type: String
    Default: 10.0.0.0/19
  KeyPairName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs allow you to securely connect to your instance after it launches.
    Default: CFT-Test
  FeInstanceType: 
    Description: Amazon EC2 instance type for the fe nodes.
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
  LogDir:
    Description: Dir to save log, please to fill in the absolute path
    Type: String
    Default: To be determined
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  MetaDir:
    Description: Dir to save mete data, please to fill in the absolute path
    Type: String
    Default: To be determined
  HttpPort:
    Description: Fe http port
    Type: String
    Default: To be determined
  RpcPort:
    Description: Fe rpc port
    Type: String
    Default: To be determined
  QueryPort:
    Description: Fe query port
    Type: String
    Default: To be determined
  EditLogPort:
    Description: Fe edit log port
    Type: String
    Default: To be determined
  MysqlServiceNioEnabled:
    Description: Mysql service nio enabled
    Type: String
    Default: True
    AllowedValues: 
      - True
      - False
  EnableSparkLoad:
    Description: Enable spark load
    Type: String
    Default: True
    AllowedValues: 
      - True
      - False
  SparkHomeDefaultDir:
    Description: Spark home default dir, please to fill in the absolute path
    Type: String
    Default: To be determined
  YarnClientPath:
    Description: Yarn client path, please to fill in the absolute path
    Type: String
    Default: To be determined
  CatalogTrashExpireSecond:
    Description: Catalog trash expire second
    Type: String
    Default: To be determined
  LogRollSizeMb:
    Description: Log roll size mb
    Type: String
    Default: To be determined
  SysLogRollNum:
    Description: Sys log roll num
    Type: String
    Default: To be determined
  AuditLogDir:
    Description: Audit log dir
    Type: String
    Default: To be determined
  AuditLogModules:
    Description: Audit log modules
    Type: String
    Default: To be determined
  MetaDelayTolerationSecond:
    Description: Meta delay toleration second
    Type: String
    Default: To be determined
  QeMaxConnection:
    Description: Qe max connection
    Type: String
    Default: To be determined
  MaxConnPerUser:
    Description: Max connPerUser
    Type: String
    Default: To be determined
  QeQueryTimeoutSecond:
    Description: Qe query timeout second
    Type: String
    Default: To be determined
  QeSlowLogMs:
    Description: Qe slow log ms
    Type: String
    Default: To be determined
  LabelKeepMaxSecond:
    Description: Label keep max second
    Type: String
    Default: To be determined
  EnableNewPlanner:
    Description: Enable new planner
    Type: String
    Default: True
    AllowedValues: 
      - True
      - False
  StreamLoadDefaultTimeoutSecond:
    Description: StreamLoad default timeout second
    Type: String
    Default: To be determined
  TabletCreateTimeoutSecond:
    Description: Tablet create timeout second
    Type: String
    Default: To be determined
  MaxCreateTableTimeoutSecond:
    Description: Max create table timeout second
    Type: String
    Default: To be determined
  ThriftClientTimeoutMs:
    Description: Thrift client timeout ms
    Type: String
    Default: To be determined
  CatalogTryLockTimeoutMs:
    Description: Catalog try lock timeout ms
    Type: String
    Default: To be determined
  IgnoreUnknownLogId:
    Description: Ignore unknown logId
    Type: String
    Default: True
    AllowedValues: 
      - True
      - False
  LatestAmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: String
    Default: ami-0d1a988128feef741
Resources:
  FeInstance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install be instance replica 1
      AWS::CloudFormation::Init:
        install_server:
          files:
            "/var/www/html/index.html":
              content: |
                Hello world!
              mode: 000644
              owner: centos
              group: centos
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref FeInstanceType
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource FeInstance --region ${AWS::Region}
          cd /home/ec2-user/starrocks/StarRocks-2.0.1/fe
          mkdir -p meta
          source /etc/profile
          bin/start_fe.sh --daemon
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource FeInstance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT60M"
Outputs:
  FeInstance:
    Description: fe instance
    Value: !Ref FeInstance
  FeInstancePrivateIp:
    Value: !GetAtt FeInstance.PrivateIp