AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks on Amazon Web Services in a new VPC.'
Metadata:
  LICENSE: Apache License Version 2.0
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying StatRocsk into an new VPC"
    Order: "1"
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Environment configuration
      Parameters:
      - LatestAmiId
      - JDKDownLoadURL
      - StarRocksDownLoadURL
    - Label:
        default: EC2 configuration
      Parameters:
      - KeyPairName
    ParameterLabels:
      LatestAmiId:
        default: Reference the latest Amazon Linux AMI in a CloudFormation template
      JDKDownLoadURL:
        default: URL of download JDK 1.8
      StarRocksDownLoadURL:
        default: URL of StarRocks
      KeyPairName:
        default: Key pair name
Parameters:
  LatestAmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: String
    Default: ami-0d648a61f4ab8d0e2
  JDKDownLoadURL:
    Description: URL of download JDK 1.8
    Type: String
    Default: https://cdn-thirdparty.starrocks.com/java-se-8u41-ri.tar.gz
  StarRocksDownLoadURL:
    Description: URL of StarRocks
    Type: String
    Default: https://www.starrocks.com/zh-CN/download/request-download/12
  KeyPairName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs allow you to securely connect to your instance after it launches.
    Default: CFT-Test
    
Resources:
  BeInstance1:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install be instance replica 1
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource BeInstance1 --region ${AWS::Region}
          
          mkdir /home/starrocks
          cd /home/starrocks

          wget ${JDKDownLoadURL} -O java.tar.gz
          mkdir ./jdk && tar -zxvf java.tar.gz -C ./jdk --strip-components 1
          mkdir /usr/java && mv jdk /usr/java
          echo 'export JAVA_HOME=/usr/java/jdk' >> /etc/profile
          echo 'export JRE_HOME=/usr/java/jdk/jre' >> /etc/profile
          echo 'export CLASSPATH=.:/usr/java/jdk/lib:/usr/java/jdk/jre/lib:$CLASSPATH' >> /etc/profile
          echo 'export JAVA_PATH=/usr/java/jdk/bin:/usr/java/jdk/jre/bin' >> /etc/profile
          echo 'export PATH=$PATH:/usr/java/jdk/bin:/usr/java/jdk/jre/bin' >> /etc/profile
          source /etc/profile
          rm -rf java.tar.gz

          yum install MySQL-python.x86_64 -y
          yum install mysql -y

          mkdir -p /home/starrocks/tool
          echo '#!/usr/bin/python' >> /home/starrocks/tool/addBeTool.py
          echo '# -*- coding: UTF-8 -*-' >> /home/starrocks/tool/addBeTool.py
          echo 'import MySQLdb' >> /home/starrocks/tool/addBeTool.py
          echo 'import sys' >> /home/starrocks/tool/addBeTool.py
          echo 'import time' >> /home/starrocks/tool/addBeTool.py
          echo 'import os' >> /home/starrocks/tool/addBeTool.py
          echo 'time.sleep(30)' >> /home/starrocks/tool/addBeTool.py
          echo 'db = MySQLdb.connect(host = '"'"'127.0.0.1'"'"', user = '"'"'root'"'"', passwd = '"'"''"'"', port = 9030, connect_timeout=10)' >> /home/starrocks/tool/addBeTool.py
          echo 'cursor = db.cursor()' >> /home/starrocks/tool/addBeTool.py
          echo 'for index in range(len(sys.argv)):' >> /home/starrocks/tool/addBeTool.py
          echo '    if index == 0:' >> /home/starrocks/tool/addBeTool.py
          echo '        continue' >> /home/starrocks/tool/addBeTool.py
          echo '    if sys.argv[index] != '"'"'0.0.0.0'"'"':' >> /home/starrocks/tool/addBeTool.py
          echo '        cursor.execute("ALTER SYSTEM ADD BACKEND '"'"'%s:9050'"'"'"%sys.argv[index])' >> /home/starrocks/tool/addBeTool.py
          echo 'data = cursor.fetchone()' >> /home/starrocks/tool/addBeTool.py
          echo 'db.close()' >> /home/starrocks/tool/addBeTool.py
          chmod +x /home/starrocks/tool/addBeTool.py

          wget ${StarRocksDownLoadURL} -O starrocks.tar.gz
          mkdir ./StarRocks && tar -zxvf starrocks.tar.gz -C ./StarRocks --strip-components 1
          rm -rf starrocks.tar.gz

          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource BeInstance1 --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT10M"